#!/usr/bin/env python3

import colors as c
import random 

print(c.clear)
print(c.rc() + '''
I IS BALL OF DE MAGIC 8 ASK ME YOUR MIND AND I WILL RESPOND.''')

answers = [
    'No Your not',
    'Its a lie',
    'Sorry pal',
    'error 404',
    'Yes',
    'pardon?',
    'Most likely',
    'Definetly',
    'JUST, DO IT',
    '(.Y.)',
    '(._.)',
    'Goodbye come again'
]

def ask(prompt):
    answer = input(prompt).strip().lower()
    return answer

def bye(prompt):
    answer = input(prompt).strip().lower()
    print(c.rc() + answer + c.reset)
    exit()

def handle_question():
    question = ask("SPEAK ")
    if 'swag' in question: 
        print(c.rc() + "The day of your birth is modern") 
    elif 'love' in question:
        print(c.red + '''error, value "Love" dose not compute''')
    elif 'bye' in question:
        print(c.rc() + answer + c.reset)
        exit()
    else:
        answer = random.choice(answers)
        print(c.rc() + answer + c.reset)

while True:
    try: 
        handle_question() 
    except KeyboardInterrupt:
        print()
        print("Well if you want to leave so badly goodbye!")
        exit()

